spring:
    datasource:
        url: jdbc:h2:~/enrollment;AUTO_SERVER=true;MODE=MySQL;DATABASE_TO_LOWER=TRUE
        driver-class-name: org.h2.Driver
        username: sa
        password:
    sql:
        init:
            mode: always
            data-locations:
    jpa:
        database: h2
        generate-ddl: false
        database-platform: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: create-drop
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        open-in-view: false
    h2:
        console:
            enabled: true
            path: /h2-console
logging:
    config: classpath:logback-local.xml

server:
    port: 8080
    shutdown: graceful

management:
    endpoints:
        web:
            base-path: /monitor
            path-mapping:
                health: /health
                prometheus: /metrics
            exposure:
                include: health, prometheus
    health:
        defaults.enabled: false
        ping.enabled: true
    endpoint:
        health.probes.enabled: true
        prometheus.enabled: true
    server:
        port: 9115
